
# required for this CI Pipeline:
#   - squizlabs/php_codesniffer
#   - phpstan.neon file
# recommended: captainhook/captainhook
        

default:
  image: thomasschaller/php-cli:8.2

stages:
  - test

cache:
  paths:
   - vendor/

test_phpunit:
  stage: test
  script:
    - composer install
    - composer test

test_quality:
  script:
    - composer install
    - vendor/bin/phpcs --standard=PSR12 -n src
    - composer check-static
